# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
#
require 'factory_bot_rails'

title_1 = "Tantra, 'Hills of Katmandu' (Philips, 1979)"
title_2 = "Karen Young, 'Hot Shot' (West End, 1978)"
title_3 = "Trilogy, 'Not Love' (Il Discotto, 1982)"
title_4 = "Alexander Robotnick, 'Problemes d'Amour' (Fuzz Dance, 1983)"
title_5 = "D-Train, 'You're the One for Me' (Prelude, 1981)"
title_6 = "Klein & MBO, 'Dirty Talk' (Zanza, 1982)"
title_7 = "Sylvester, 'I Need Somebody to Love Tonight' (Fantasy, 1979)"
title_8 = "Black Devil, Disco Club (RCA, 1978)"
title_9 = "Gino Soccio, ' Dancer' (RFC/Warner, 1979)"
title_10 = "ESG, 'Moody' (99 Records, 1981)"
title_11 = "Kano, 'I'm Ready' (Emergency, 1980)"
title_12 = "Taana Gardner, 'Heartbeat' (West End, 1981)"
title_13 = "Grace Jones, 'Pull Up to the Bumper' (Island, 1981)"
title_14 = "Loose Joints, 'Is It All Over My Face?' (West End, 1980)"
title_15 = "Dinosaur L, 'Go Bang!' (Sleeping Bag, 1982)"
title_16 = "First Choice, 'Love Thang' (Gold Mind, 1979)"
title_17 = "Double Exposure, 'Ten Percent' (Salsoul, 1976)"
title_18 = "Stevie Wonder, 'As' (Tamla, 1976)"
title_19 = "Carl Bean, 'I Was Born This Way' (Motown, 1977)"
title_20 = "Cloud One, 'Atmosphere Strut' (P&P, 1976)"
title_21 = "Manu Dibango, 'Soul Makossa' (Atlantic, 1972)"
title_22 = "Giorgio Moroder, 'The Chase' (Casablanca, 1978)"
title_23 = "Chicago, 'Street Player' (Columbia, 1979)"
title_24 = "The Clash, 'The Magnificent Dance' (Epic, 1981)"

body_1 = "By early 1980, most U.S. record companies dropped all but disco's biggest acts and redirected its superstars to rock, pop, and R&B. But gay dancers still wanted more of the speedy, otherworldly Eurodisco that took them to another planet, a safe one far away from Anita Bryant, Harvey Milk assassin Dan White, and all the other homophobes of the era. Tantra's 1979 16-minute opus 'Hills of Katmandu' did exactly that — especially if you were tripping your balls off. Recorded before Italian disco morphed into Italo disco, 'Katmandu' placed willing dancers high, high, high atop the mountains of Nepal. Italian arranger Celso Valli packs the track with undulating bass, snake-charmer synths, bongos aplenty, hard-rock guitar power chords, and choirs evoking the Munchkins of Oz. Giorgio Moroder associate Jürgen Koppers mixed the result for maximum hallucinatory effect. BARRY WALTERS"
body_2 = "Classic, unapologetically disco disco — as opposed to 'not really actually disco, y'know' disco — has swept back into the public eye over the last decade. That's meant a newfound fever for records like 'Hot Shot,' a glaring gem, manic and frankly sex-crazed, from New York's West End Records which, along with the Salsoul label, carried the flame for quality underground dance music right after disco's public American 'death.' But house music in the '90s sampled the music right back to life — 'Hot Shot,' in particular, gained a new audience thanks to none other than Daft Punk, who cut it up on 'Indo Silver Club,' from 1997's Homework. MICHAELANGELO MATOS"
body_3 = "When American disco ran aground in the late '70s, enterprising Chicago DJs like Frankie Knuckles and Ron Hardy began looking to the import section to fortify their all-night sessions — in particular, they looked to 'Italo disco,' earnestly sung post-'I Feel Love' synth-scapes from Giorgio Moroder's native Italy. Trilogy, an alias of prolific producer Paolo Micioni, who usually worked with his brother Peter, produced 1982's 'Not Love,' a model of the style. It was a big favorite of Herb Kent, who'd spin the track on his influential late-night Chicago radio show 'Tune In and Punk Out' — a crucial influence on the city's early house producers. The silvery synths and deliberate pacing echoes in much of the largely Scandinavian wing of vista-ridden neo-disco as well. M.M."
body_4 = "Translated from its original French, 'Problemes d'Amour' is like what Blade Runner's Roy Batty would cut loose to in a Rimini discotheque: 'Oh! This is the cry of a robot in love, oh / Oh! Even without tears, he cries always, oh.' Alexander Robotnick was the alias of Maurizio Dami, a cabaret singer from Florence who programmed his way into dance music's history books with this quixotic ode to robotic romance. The third release on the short-lived Fuzz Dance label, the track paired sing-songy chants and fluttery funk synthesizers with a crisp machine groove halfway between Kraftwerk and Cybotron. In both its instrumentation and its cadence, it has as much to do with electro-funk as disco, and its wriggly 303 line anticipates Chicago acid, then just around the corner. But arriving just as Italo disco was becoming a recognized thing, it also represents a crucial moment in the way disco mutated as it traveled, reaching Europe as its stateside popularity waned, and then boomeranging back to our shores in a newly streamlined, mechanized format. Fun fact: That's 'Problemes d'Amour' playing in the topless-bar scene in National Lampoon's European Vacation. PHILLIP SHERBURNE"
body_5 = "Instead of the rolling, gliding rhythm of canonical disco, producer Hubert Eaves III's punchy drums and synth vamps hewed closer to funk's stepping, strutting cadences. Disco was effectively over by the time Jimmy Carter left office. Facing a recession, bloated budgets, and a market flooded with inferior product — not to mention the growing backlash, which culminated in 1979's record-burning 'Disco Demolition Night' in Chicago — the major labels slashed payrolls and shuttered disco departments. But, says Village Voice columnist Vince Aletti, 'a lot of the records that came out after that period I thought were really stronger. They didn't have to fit into a mold. They were less and less formulaic.' And that's certainly true of this shiny, synthy, funk hybrid. P.S."
body_6 = "This skeletal synth jam, slightly fleshed out by nervous punk-funk guitar scratches, was one of very few Italo-disco imports played upon release in 1982 by the same New York DJs who mostly spun the R&B shades of latter-day disco. Roland synths hum and 808 beats percolate so hypnotically that many jocks still opt for the instrumental mixes, but the 11-minute 'USA Connection' version is where the hardcore action happens. 'Cast your fate up to the sky / 'Cause now it's time to say goodbye,' helium-voiced jazz singer Rosanna Casale warbles with nearly violent intent until much later collapsing in a fit of goofy baby giggles. The dirty talk is all implied, but nevertheless tangible: There's a weirdness here that feels forbidden, like photos you know you shouldn't be looking at but nevertheless hold you in their spell. B.W."
body_7 = "Former member of the city's notorious hippie-drag performing commune the Cockettes, Sylvester James Jr. added synthesizer wizard Patrick Cowley to his band, discovering the essential ingredient that would take his new disco direction to the stratosphere via 1978 anthems 'Dance (Disco Heat)' and 'You Make Me Feel (Mighty Real).' For the 1979 LP Stars, Sylvester sang two Cowley compositions, the radiant title track, and this last one. Set at the tempo of dejected yet desirous feet walking home alone, 'I Need Somebody to Love Tonight' feels like a stroll down a dimly lit alleyway of adventure. There isn't much more to the lyric than the title, but that's the point: Raw physical need can take hold of your soul so badly that there's literally nothing else, or so it seems, and Sylvester and Cowley embody that single-mindedness with a synthesizer strut and a melancholy jazz sigh. This is the sound of sleaze, the early morning, the lower BPM soul groove with which disco-era DJs would send dancers home. It was a thread picked up by Italy's cosmic scene, Ibiza's Balearic beat, and kindred slow-mo disco followers everywhere. B.W."
body_8 = "Aphex Twin's Rephlex label helped kick off disco's revival in 2004 when it reissued Disco Club, a 1978 album by French producer Bernard Fevre that was so obscure that many listeners wondered if the whole thing was an elaborate prank. The album's six tracks of chugging, robotic Eurodisco are so similar in sound and mood that the album comes across less as a collection of songs than a six-track suite threaded together by bubbling synth arpeggios and Fevre's peculiar, almost lumpy drum and percussion patterns. It was almost certainly inspired by Giorgio Moroder's From Here to Eternity from the previous year, but Black Devil's clammy dungeon atmospheres and ghostly whoops have even more in keeping with Giallo schlock jocks like Goblin — a perfect forebear to the retrofuture pulse of Lindstrøm and a direct heir to groups like Gatekeeper and Zombi. P.S."
body_9 = "Quebec is the closest thing to a European outpost you'll find on North American soil, so it's not too surprising that Gino Soccio, an Italian-Canadian musician from Montreal, so skillfully fused the soulful qualities of American R&B with the sleekness of Eurodisco. He stumbled upon disco by chance: A fan of Kraftwerk and Stockhausen known as the go-to guy for anything synth-related, he caught disco fever when local producer Pat Deserio hired him to record a disco version of Ravel's 'Bolero' under the name Kebekelektrik. Seeing dancers' response to 'War Dance,' an original that he had tucked on the B-side, emboldened him to try his hand at an album-length statement, Dancer. But it was the title track and lead single that made Soccio's name, thanks to its fusion of gritty funk riffs, dance floor-stoking vocals, and shimmering electronic touches. At the Paradise Garage, Soccio told Wax Poetics, Larry Levan 'would play that song three times in a row sometimes, and it was already an eight-minute disco song. It was 24 minutes of 'Dancer,' and people just would not get enough of it.' The song's extended breakdown, straining liquid keys through a bare-bones beat, is a direct antecedent of the deep house that would arrive with Larry Heard and Kevin Saunderson, a style that has returned with a (gentle) vengeance in both underground (DJ Koze) and overground (Disclosure) alike. P.S."
body_10 = "ESG were hardly a conventional 'disco' act in any sense of the word. The South Bronx's Scroggins sisters came on the scene in 1981 with a skeletal, sui generis take on funk that didn't so much trim it down as scorch away every last ounce of excess. That they played both the opening night of Manchester's Hacienda and the closing night of New York's Paradise Garage seems almost too perfect, given the way tha tthey bridged two vastly different undergrounds. They were signed 99 Records, then home to  feedback monumentalist Glenn Branca and scrappy punk-funk minimalists Bush Tetras, and their debut EP was produced by Factory Records' Martin Hannett, who discovered them when they opened for A Certain Ratio. They've been re-discovered many times since then — by Public Enemy, N.W.A., Tricky, Franz Ferdinand, and scores of other artists who found their spooky, sinewy, meat-freezer funk to be the perfect source for a juicy sample. 'Moody' treated disco less as a genre than a state of mind, like the scent of autumn hanging in the air as no wave's chill descended — you can hear it in the barely-there grooves of Factory Floor, the Soft Moon, and S.C.U.M. P.S."
body_11 = "The near-falsetto vocal trill, slippery hi-hats, lean claps, and burbling synthesizers of this roller-funk forerunner to Italo disco made it both a great novelty and an example of solid craftsmanship — not to mention a hit, both with DJs (it was a favorite at the Paradise Garage) and on black radio, going to No. 21 R&B in 1981. Not bad for three Italians riding the end of Disco Mk 1's timeline. But it's the garbled voice box on the chorus that puts this in the DJ canon. It wasn't the first or the best vocoder record in dance music — certainly not the last. But it was one of the most humane — a seed for both techno elegance and Daft Punk's pinging warmth. M.M."
body_12 = "So slow and strange that it initially cleared the floor at the otherwise notoriously progressive, permissive Paradise Garage, this testimonial of desire and devotion was such a favorite of Larry Levan that he mixed it himself until it became the most aesthetically underground R&B jam of the '80s to achieve overground success. It's seriously, delectably off-kilter: Newark-born singer Taana Gardner's heart, represented by a lurching bass drum, seems as though it could have an attack at any moment from the sheer acuteness of her love, as well as from the groove's queasy dub-shaded funk. 'Now you know this makes no kinda sense / Walkin' 'round here so intense,' she admits midway, knowing full well that what's irrational — represented by every brooding note of this nine-and-a-half-minute epic — is often what's right. B.W."
body_13 = "Seemingly genetically engineered to represent everything about disco in living physical form, Jamaican-American model Grace Jones spent the first few years of her singing career belting — in her severe way — an über-urbane variant on the Philly disco that was remixing pioneer Tom Moulton's specialty. In 1980, she abruptly switched to a disco/funk/reggae/new-wave fusion with Jamaican rhythm section extraordinaire Sly Dunbar and Robbie Shakespeare, and perfected it on her feted Nightclubbing album the next year, which featured the disco song for which she's most known. Taking rock'n'roll's 'driving = sex' equation to unprecedented levels of explicitness via an extended metaphor that culminates with the gloriously direct come-on 'let me lubricate it,' 'Pull Up to the Bumper' thrusts and wiggles like intercourse itself. B.W."
body_14 = "When the mainstream turned its back on disco at the dawn of the '80s, it allowed clubland to once again wander down any damn path it chose. Born in Oskaloosa, Iowa, downtown Manhattan-based cellist Arthur Russell routinely chose paths that had the most left turns. The original male vocal mix of this lusty, raucous record, concocted by Russell and fellow disco vanguard denizen Steve D'Aquisto, features bongos so ridiculously loud and piercing that your needle might jump a groove. Larry Levan's subsequent female vocal mix is still freaky: Melvina Woods, a dancer found at kindred NYC club the Loft, slurs and misses notes as if her own loose joints were dusted, but the animalistic groove is so undeniably in-the-pocket that this actually got local radio play back in the day and remains in constant cult club rotation today. Ten years later, Roger Sanchez (as the Underground Solution) had a bigger hit with his fabulous, vogue-ready house remake 'Luv Dancin',' but nothing beats the original's squawking funk. B.W."
body_15 = "Released on Dinosaur L's 1981 album 24→24 Music and dubbed the fuck out by Francois K. for 12-inch the following year, 'Go Bang!' is a snapshot of Downtown avant-disco polymath Arthur Russell at his most elegantly unhinged. The album version kicks off with a few minutes of stringy country-disco overlaid with warbly non sequiturs ('I wanna see all my friends at once / I need an armchair to put myself in your shoes') before swarming organs and fat, dissonant daubs of Rhodes turn it into free jazz with a stonkin' oonce-oonce beat. Francois K.'s edit is part surgeon, part madman, making cat's cradles out of the connective tissue between the song's wildly divergent parts. Chants that might have scanned as nostalgic, in another context, come off as urgent, almost angry. 'I'd do anything to get the chance to go back / I wanna go back!' And later, again, 'I wanna see all my friends at once!' It's hard, now, not to read that as a premonition of the way disease would lay waste to a huge swath of the community that made all this possible, including Russell himself. But whatever nostalgia may have driven the song's lyrical content — obviously, in the process, paving the way for LCD Soundsystem's 'All My Friends' — there was no looking backward. P.S."
body_16 = "How much mileage can you get out of two chords? Plenty, according to Philadelphia vocal trio First Choice (Rochelle Fleming, Joyce Jones, and Annette Guest), as evidenced on this hypnotic 1979 number, backed by members of the Salsoul Orchestra and MFSB. The chorus is as ecstatic as you'd expect from a group with gospel roots, but they get it out of the way almost immediately, blowing through twice before the tune is anywhere near the two-minute mark; the vast majority of the track is just a crisply stepping up-and-down figure, with the three singers growling hungrily over a rhythm section that treats 'tight' and 'loose' as two sides of a coin sent spinning across the table. Eugene 'Lambchops' Curry's funky keyboard vamping is the secret star of the whole thing (no wonder Carl Craig borrowed it for the hook of his 1990 cut 'The Climax'). The breakdown and re-build of the song's latter third anticipates the kind of filter tricks that Daft Punk would turn into a cottage industry. And, of course, the chorus would be sampled by Chubb Rock for one of Barack and Michelle Obama's favorite songs. P.S."
body_17 = "There are few records more pivotal in the history of dance music than Double Exposure's 'Ten Percent.' To help push the Philadelphia group's debut single, the Salsoul label decided to press it on both 7-inch vinyl and the nascent 12-inch format, which thus far had been used only in the case of a few select DJ-only promos. To make the commercial debut of the format, Salsoul turned to New York DJ Walter Gibbons, a scarily talented mixer who had begun juggling percussive breaks around the same time that DJ Kool Herc was inventing hip-hop with doubles of 'Apache.' Radically reshaping the cut (much to the consternation of songwriter Allan Felder), Gibbons turned four minutes of ballooning, string-laden soul into nearly 10 minutes of careening percussion and climax after climax — a perfect template for producers like Timbaland who have mixed their generation's contemporary beats with mirror-ball moods. Salsoul released the record to the public in a die-cut sleeve and pressed at 45 RPM, avoiding the gaping empty space that would have resulted from just one cut pressed at 33 on a single side of vinyl. Consumers clearly didn't mind: Priced at $2.98, the 'giant single' sold 110,000 copies in a single week. The 12-inch — and the remix — were here to stay. P.S."
body_18 = "The most fecund musician of the '70s layered this gospel-soul masterpiece — the grandest climax of the many that festooned 1976's Songs in the Key of Life — while keeping the groove constant. (And constantly surprising — this may be Wonder's greatest drumming performance, no small accolade.) Not that Stevie's ever moved far from the voices of male R&B stars who have aped his tics for decades. (Wonder's Jungle Fever soundtrack was mere payback for all that New Jack Swing took from him.) And the widescreen, analog ambition of his '70s work informs everything from neo-soul to the current breed of post-Internet R&B shapeshifters. M.M."
body_19 = "In 1975, enterprising Harlem businesswoman Bunny Jones decided to help the gay friends she'd made while owning several beauty salons. 'I began to feel that gays are more suppressed than blacks, Chicanos or other minorities,' she told The Advocate that year. 'You hear of great designers or famous hairdressers, and that's about as far as society will let gays go.' So she co-wrote this proud protest song, releasing the Valentino-sung original on her own Gaiee Records, and scored distribution from Motown founder Berry Gordy. Two years later, Gordy released a far more emphatic version on his own label that was played and produced by Philly's MFSB posse. 'I'm happy, I'm carefree, and I'm gay / I was born this way,' belts (future founding prelate of the Unity Fellowship Church Movement) Carl Bean with a gospel fervor that takes the song subversively and quite lovingly to church. B.W."
body_20 = "Has there ever been a more perfect marriage of lyrics and music than this 1976 single from Patrick Adams? 'We're gonna fly, fly away,' goes the rising chorus, and if the song's spongy, aerated groove doesn't already make you feel like you're walking on air, Adams' soaring synthesizer ensures an airborne dance floor. From his Cloud One alias to songs like 'Atmosphere Strut' and the backmasked percussion of LP cut 'Spaced Out,' it was obvious that Adams and executive producer Peter Brown were intent upon summoning the most buoyant of altered states. The subsequent mix of hazy-yet-human, distinctly mid-'70s synths are the electric sheep that robots like Daft Punk dream about. P.S."
body_21 = "African saxophonist Dibango's biggest hit was exactly what it claimed to be: the Cameroonian dance style makossa, mixed with American R&B. But when David Mancuso of the foundational New York after-hours party the Loft discovered the track in a Brooklyn record bin in 1972, he accidentally transformed it into something else entirely. 'Soul Makossa' was arguably the first disco hit — reaching No. 35 on Billboard's Hot 100, broken by a nightclub rather than a radio DJ (Frankie Crocker began playing it on WBLS-FM in New York after Mancuso). Its chant of 'ma-mako, mama-say, mama-makossa' has never left the landscape, from Michael Jackson's 'Wanna Be Startin' Somethin'' (Dibango settled out of court after filing a copyright-infringement suit) to Ariel Pink's Haunted Graffiti's 'Farewell American Primitive' — a legacy so wide-ranging that you'd need a map to sort it out. M.M."
body_22 = "If anyone could make getting locked up in a Turkish prison sound appealing, it would be Giorgio Moroder. The lead song on the soundtrack to Oliver Stone's 1978 film Midnight Express followed the sinewy, robo-disco template that Moroder had pioneered the previous year with Donna Summer's 'I Feel Love,' stretching out his streamlined arpeggio and buoyant pads for eight-and-a-half minutes (and, on the 12-inch, more than 13 minutes), with just enough melody to land the instrumental at No. 33 on the Billboard Hot 100. Euro to the core, the gliding disco beat carries a faint whiff of krautrock's dry, almost chalky drum sounds. Ironically, actual (or former, anyway) krautrockers Kraftwerk released a nearly identical song, 'The Model,' the very same year. That the two tracks should appear within five months of each other is surely one of the greatest, most mysterious instances of mind-meld synchronicity in the history of pop. The chilly atmospherics of the Italians Do It Better label and the Drive soundtrack start here. P.S."
body_23 = "Co-written by Chicago drummer Danny Seraphine, but originally cut by Rufus and Chaka Khan, 'Street Player' is notable for two reasons: It's on one of Chicago's few non-numbered albums (1978's Hot Streets), and its huffing, puffing horn chart and Peter Cetera's freakish shout of 'These sounds fall into my mi-i-i-i-ind!' In 1994, the Bucketheads — Brooklyn house producer Kenny 'Dope' Gonzalez, on break from his Masters at Work production partner Little Louie Vega — turned those snippets into the aptly titled 'The Bomb!' Those horns have remained one of house music's go-to memes — not to mention a pop one, thanks to Pitbull folding them into 'I Know You Want Me (Calle Ocho),' a No. 2 hit in 2009. M.M."
body_24 = "The Clash’s approach to everything from reggae to funk was just as sure as their grasp of punk. This 1981 B-side includes instrumental grooves that could alter the temperature of any post-disco dance floor. A voiceless dub of “The Magnificent Seven,” Joe Strummer’s hip-hop goof that led off 1980’s triple-LP Sandinista!, “The Magnificent Dance” was intended to be rapped over, à la Sugar Hill Records’ 12-inch flipsides. Instead, it became a club hit after the group began sending 12-inches to DJs, scoring airplay from Frankie Crocker on WBLS-FM, New York’s number-one R&B station, and snaking its way into sets throughout the Chicago and New York DJ undergrounds. It sounded equally fresh in the milieu of 2000s post-punk redux. Today, it’s as firmly established a classic dance track as London Calling is a classic rock album. M.M."


Article.create!(title: title_1, body: body_1, created_at: (rand(5000000)).minutes.ago)
Article.create!(title: title_2, body: body_2, created_at: (rand(5000000)).minutes.ago)
Article.create!(title: title_3, body: body_3, created_at: (rand(5000000)).minutes.ago)
Article.create!(title: title_4, body: body_4, created_at: (rand(5000000)).minutes.ago)
Article.create!(title: title_5, body: body_5, created_at: (rand(5000000)).minutes.ago)
Article.create!(title: title_6, body: body_6, created_at: (rand(5000000)).minutes.ago)
Article.create!(title: title_7, body: body_7, created_at: (rand(5000000)).minutes.ago)
Article.create!(title: title_8, body: body_8, created_at: (rand(5000000)).minutes.ago)
Article.create!(title: title_9, body: body_9, created_at: (rand(5000000)).minutes.ago)
Article.create!(title: title_10, body: body_10, created_at: (rand(5000000)).minutes.ago)
Article.create!(title: title_11, body: body_11, created_at: (rand(5000000)).minutes.ago)
Article.create!(title: title_12, body: body_12, created_at: (rand(5000000)).minutes.ago)
Article.create!(title: title_13, body: body_13, created_at: (rand(5000000)).minutes.ago)
Article.create!(title: title_14, body: body_14, created_at: (rand(5000000)).minutes.ago)
Article.create!(title: title_15, body: body_15, created_at: (rand(5000000)).minutes.ago)
Article.create!(title: title_16, body: body_16, created_at: (rand(5000000)).minutes.ago)
Article.create!(title: title_17, body: body_17, created_at: (rand(5000000)).minutes.ago)
Article.create!(title: title_18, body: body_18, created_at: (rand(5000000)).minutes.ago)
Article.create!(title: title_19, body: body_19, created_at: (rand(5000000)).minutes.ago)
Article.create!(title: title_20, body: body_20, created_at: (rand(5000000)).minutes.ago)
Article.create!(title: title_21, body: body_21, created_at: (rand(5000000)).minutes.ago)
Article.create!(title: title_22, body: body_22, created_at: (rand(5000000)).minutes.ago)
Article.create!(title: title_23, body: body_23, created_at: (rand(5000000)).minutes.ago)
Article.create!(title: title_24, body: body_24, created_at: (rand(5000000)).minutes.ago)

@comment_1 = "Wow that was a really great article, I very much enjoyed it!!!"
@comment_2 = "Not so big on this one, it leaves a little to be desired"
@comment_3 = "This makes me wanna DANCE!"
@comment_4 = "Who comes up with this sort of stuff??"
@comment_5 = "I absolutely love disco, thanks for sharing"
@comment_6 = "I forgot my lunch at home and all I got was this lousy blog out of it"
@comment_7 = "Great stuff!! Let's do it again sometime"
@comment_8 = "Whoa!! This guy really built a cool product, and I love being a member!! I bet somebody hires him quick!"
@comment_9 = "I could really do without this sort of thing"
@comment_10 = "What a great dance tune!!"
@comment_11 = "I can't stop listening to this track!!!"

@comment_array = [@comment_1, @comment_2, @comment_3, @comment_4, @comment_5, @comment_6, @comment_7, @comment_8, @comment_9, @comment_10, @comment_11]

@user_1 = User.create(name: "Glynnis", email: "test_1@gmail.com", password: "password", city: "Boise", state: "ID", street_address: "11482 Ridgecrest Dr.", recurring: true, role: 0, zip_code: "86517")
@user_2 = User.create(name: "Corey", email: "test_2@gmail.com", password: "password", city: "Baltimore", state: "MD", street_address: "981 Ashcroft Ln.", recurring: true, role: 0, zip_code: "76523")
@user_3 = User.create(name: "Mills", email: "test_3@gmail.com", password: "password", city: "Chicago", state: "IL", street_address: "724 Briarwood Dr.", recurring: true, role: 0, zip_code: "97253")
@user_4 = User.create(name: "Noah", email: "test_4@gmail.com", password: "password", city: "Gunnison", state: "CO", street_address: "2540 Osuego Pl.", recurring: true, role: 0, zip_code: "83647")
@user_5 = User.create(name: "Jeremy", email: "test_5@gmail.com", password: "password", city: "Ventura", state: "CA", street_address: "1340 Princeton Ave.", recurring: true, role: 0, zip_code: "98362")
@user_6 = User.create(name: "Matt", email: "test_6@gmail.com", password: "password", city: "Dover", state: "DE", street_address: "8294 Grove St.", recurring: true, role: 0, zip_code: "37624")
@user_7 = User.create(name: "Alexandra", email: "test_7@gmail.com", password: "password", city: "Providence", state: "RI", street_address: "1941 Turnley Pl.", recurring: true, role: 0, zip_code: "29013")
@user_8 = User.create(name: "Miguel", email: "test_8@gmail.com", password: "password", city: "Grand Rapids", state: "MI", street_address: "622 Boston Ave.", recurring: true, role: 0, zip_code: "39047")

@users_array = [@user_1, @user_2, @user_3, @user_4, @user_5, @user_6, @user_7, @user_8]

1.upto(300).each do |num|
  comment = @comment_array.sample 
  user = @users_array.sample
  article = Article.all.sample
  time_diff = Time.current - article.created_at
  num = rand(time_diff / 1.minute).floor
  Comment.create(body: comment, user_id: user.id, article_id: article.id, created_at: num)
end
